# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'KPTestFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

#pod 'TestPodFramework', :git => 'https://github.com/manhlx3006/TestPodFramework.git'

  pod 'Moya', '~> 10.0.1'
  pod 'BigInt', '~> 3.1.0'
  pod 'APIKit', '~> 3.2.1'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'TrustKeystore', '~> 0.4.2'
  pod 'TrustCore', '~> 0.0.7'
  pod 'JSONRPCKit', '~> 3.0.0' # :git=> 'https://github.com/bricklife/JSONRPCKit.git'
  pod 'IQKeyboardManager', '~> 6.2.0'
  pod 'KeychainSwift', '~> 13.0.0'
  pod 'QRCodeReaderViewController', '~> 4.0.2' #:git=>'https://github.com/yannickl/QRCodeReaderViewController.git', :branch=>'master'
  pod 'JavaScriptKit', '~> 1.0'

  # Pods for KPTestFramework

  target 'KPTestFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KPTestFrameworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['JSONRPCKit'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
    if ['TrustKeystore'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
      end
    end
  end
end
